<?php

/**
 * Basesource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * @property string $link
 * @property string $author
 * @property varchar $language
 * @property Doctrine_Collection $Feeds
 * 
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getLink()        Returns the current record's "link" value
 * @method string              getAuthor()      Returns the current record's "author" value
 * @method varchar             getLanguage()    Returns the current record's "language" value
 * @method Doctrine_Collection getFeeds()       Returns the current record's "Feeds" collection
 * @method source              setTitle()       Sets the current record's "title" value
 * @method source              setDescription() Sets the current record's "description" value
 * @method source              setLink()        Sets the current record's "link" value
 * @method source              setAuthor()      Sets the current record's "author" value
 * @method source              setLanguage()    Sets the current record's "language" value
 * @method source              setFeeds()       Sets the current record's "Feeds" collection
 * 
 * @package    rssreader
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basesource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('source');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('author', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('language', 'varchar', 100, array(
             'type' => 'varchar',
             'length' => 100,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('feed as Feeds', array(
             'local' => 'id',
             'foreign' => 'source_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}