<?php

/**
 * feedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class feedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object feedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('feed');
    }
}