<?php

/**
 * sourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sourceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('source');
    }
}