<?php

/**
 * source
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rssreader
 * @subpackage model
 * @author     Krishenko Timofey
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class source extends Basesource
{
  /**
   * get rss feed
   * @param string $uri
   * @return \sfRssFeed
   */
  private function getRss($uri){
    $browser = new sfWebBrowser();
    $rssString = $browser->get($uri)->getResponseText();
   
    $rss = new sfRssFeed();    
    $rss->fromXml($rssString);
    return $rss;
  }
  
  /**
   * parren::save and set option source
   * @param \Doctrine_Connection $conn
   */
  public function save(\Doctrine_Connection $conn = null) {    
    $rss = $this->getRss($this->getLink());

    $this->setTitle($rss->getTitle());
    $this->setDescription($rss->getDescription());
    $this->setLanguage($rss->getLanguage());
    $this->setAuthor($rss->getAuthorEmail());
    
    parent::save($conn);
    $this->saveFeeds($this->getId(), $rss->getItems());
  }
  
  /**
   * save object feeds
   * @param integer $id
   * @param object $items
   */
  private function saveFeeds($id, $items){
    foreach($items as $item){
      $feed = new feed();
      $feed->setTitle($item->getTitle());
      $feed->setDescription($item->getDescription());
      $feed->setLink($item->getLink());
      $feed->setSourceId($id);
      $feed->save();
    }
  }
}
