options:
  collate: utf8_unicode_ci
  charset: utf8
    
source:
  actAs: { Timestampable: ~ }
  columns:
    title:         { type: string(255) }
    description:  { type: string(4000) }
    link:         { type: string(255), notnull: true, unique: true }
    author:       { type: string(255) }
    language:     { type: varchar(100) }   
  
 
feed:
  actAs: { Timestampable: ~ }
  columns:
    source_id:    { type: integer, notnull: true }
    title:        { type: string(255) }
    link:         { type: string(4000) }
    description:  { type: string(4000) }
    author:       { type: string(255) }
  relations:
    source: { local: source_id, foreign: id, foreignAlias: Feeds }    